version: '3.8'
services:
  backend:
    image: backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"